In [2]:
import pandas as pd
from pathlib import Path

In [4]:
datasets = Path('/home/mv18gs/Documents/GitHub/pathway_model/datasets/')
relation = pd.read_csv(datasets / 'other/relation_ohe.csv')
relation

,pathway_name,ensembl1,ensembl2,activation,binding/association,compound,dephosphorylation,dissociation,expression,glycosylation,indirect,indirect effect,inhibition,methylation,missing interaction,phosphorylation,repression,state change,ubiquitination
0,path:hsa04975,ENSG00000204310,ENSG00000067113,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
1,path:hsa04975,ENSG00000204310,ENSG00000141934,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
2,path:hsa04975,ENSG00000204310,ENSG00000162407,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,path:hsa04975,ENSG00000169692,ENSG00000067113,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,path:hsa04975,ENSG00000169692,ENSG00000141934,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75934,path:hsa00190,ENSG00000136888,ENSG00000180817,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75935,path:hsa00190,ENSG00000136888,ENSG00000107902,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75936,path:hsa00190,ENSG00000241468,ENSG00000138777,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75937,path:hsa00190,ENSG00000241468,ENSG00000180817,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75938,path:hsa00190,ENSG00000241468,ENSG00000107902,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
relation_abs_grp = relation.groupby(['ensembl1','ensembl2'], as_index=False).any()
relation_abs_grp

,ensembl1,ensembl2,pathway_name,activation,binding/association,compound,dephosphorylation,dissociation,expression,glycosylation,indirect,indirect effect,inhibition,methylation,missing interaction,phosphorylation,repression,state change,ubiquitination
0,ENSG00000000938,ENSG00000051382,True,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,ENSG00000000938,ENSG00000113263,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,ENSG00000000938,ENSG00000117461,True,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,ENSG00000000938,ENSG00000120899,True,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
4,ENSG00000000938,ENSG00000121879,True,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32793,ENSG00000278828,ENSG00000169429,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
32794,ENSG00000282608,ENSG00000065135,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32795,ENSG00000282608,ENSG00000114353,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32796,ENSG00000282608,ENSG00000127955,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32797,ENSG00000286522,ENSG00000169429,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False

In [8]:
def get_masks(relation:pd.DataFrame):
        # initialize empty dict
        mask_nodes = {}

        # iterate through df grouped by mask_id
        for mask_id, group in relation.groupby('pathway_name'):
            nodes = pd.concat([group['ensembl1'], group['ensembl2']]).unique() # get unique nodes in idx1 & idx2
            mask_nodes[mask_id] = nodes.tolist() # append to dict

        # list masks
        masks = [j for _,j in mask_nodes.items()]

        return masks

---

In [3]:
import modules.data as d

datasets = Path('/home/mv18gs/Documents/GitHub/pathway_model/datasets/')

# get data
brca = d.Data(
    # datasets
    tcga_project = 'TCGA-BRCA',
    metadata_subtype_col = 'paper_BRCA_Subtype_PAM50',

    # dirs
    tcga_dir = datasets / 'tcga',
    relation_filepath = datasets / 'other/relation_ohe.csv',
    
    # col, filter
    y_col = 'subtype',
    drop = {'subtype':['Normal', 'Metastatic']},
    max_subset=120,
)

**** Data() ****
log0_method      log1p            str
class_weights    (6,)             Tensor (cpu)
gene_counts      (4383, 567)      DataFrame
metadata         (567, 3)         DataFrame
relation         (32798, 18)      DataFrame
node_id_map      4383             dict
masks            305              list
X                (567, 4383, 1)   Tensor (cpu)
y                (567, 6)         Tensor (cpu)
y_labels         6                list
num_samples      567              int
num_nodes        4383             int
num_features     1                int
num_labels       6                int
num_masks        305              int

In [4]:
brca.relation

,idx1,idx2,activation,binding/association,compound,dephosphorylation,dissociation,expression,glycosylation,indirect,indirect effect,inhibition,methylation,missing interaction,phosphorylation,repression,state change,ubiquitination
0,0,2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
1,0,3,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
2,0,4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,0,1981,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,0,1982,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32793,3355,4381,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32794,3355,4382,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32795,3356,4380,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32796,3356,4381,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32797,3356,4382,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [34]:
brca_rel_merged = brca.relation.drop(columns='pathway_name').groupby(['idx1','idx2'], as_index=False).any()
brca_rel_merged

,idx1,idx2,activation,binding/association,compound,dephosphorylation,dissociation,expression,glycosylation,indirect,indirect effect,inhibition,methylation,missing interaction,phosphorylation,repression,state change,ubiquitination
0,0,2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
1,0,3,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
2,0,4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,0,1981,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,0,1982,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32793,3355,4381,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32794,3355,4382,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32795,3356,4380,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32796,3356,4381,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32797,3356,4382,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
brca_rel_merged[brca_rel_merged[brca_rel_merged.columns[2:]].sum(axis=1) > 1]

,idx1,idx2,activation,binding/association,compound,dephosphorylation,dissociation,expression,glycosylation,indirect,indirect effect,inhibition,methylation,missing interaction,phosphorylation,repression,state change,ubiquitination
169,6,243,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
182,7,33,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
183,7,34,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
214,7,243,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
215,7,348,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32748,3337,2361,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False
32749,3338,2361,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False
32750,3339,2361,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False
32751,3340,2361,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False
32752,3341,2361,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False

In [6]:
import torch
from pandas import DataFrame
from typing import Literal
from torch import Tensor

def _get_adj(relation:DataFrame, num_nodes:int, method:Literal['out','in']='out', source:str='idx1', target:str='idx2') -> Tensor:
    # get edge information
    edge_indices = Tensor(relation[[source, target]].values).int() # (num_edges, 2)

    # init adj
    adj = torch.zeros((num_nodes, num_nodes), dtype=torch.float32) # (num_nodes, num_nodes)

    # compute adj
    if method == 'in':
        adj[edge_indices[:,1], edge_indices[:,0]] = 1 # in_adj if specified
    else:
        adj[edge_indices[:,0], edge_indices[:,1]] = 1 # out_adj otherwise (default)

    return adj

In [12]:
brca.relation

,idx1,idx2,activation,binding/association,compound,dephosphorylation,dissociation,expression,glycosylation,indirect,indirect effect,inhibition,methylation,missing interaction,phosphorylation,repression,state change,ubiquitination
0,0,2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
1,0,3,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
2,0,4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,0,1981,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,0,1982,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32793,3355,4381,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32794,3355,4382,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32795,3356,4380,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32796,3356,4381,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
32797,3356,4382,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
_get_adj(brca.relation, brca.num_nodes)

tensor([[0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])